# Generated by Django 4.1.4 on 2022-12-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('name', models.CharField(max_length=150)),
                ('lng', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('sactioned', models.BooleanField(default=False, null=True)),
                ('security', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('username', models.CharField(max_length=24, unique=True)),
                ('password', models.CharField(max_length=1024)),
                ('dropin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropins', to='base.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacles', to='base.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('content', models.TextField(blank=True, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotcomments', to='base.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to='base.user')),
            ],
        ),
    ]
