# Generated by Django 4.1.4 on 2022-12-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
