# Generated by Django 4.1.4 on 2022-12-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dropin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropins', to='base.spot'),
        ),
    ]
